services:
  app:
    build: .docker/app
    stdin_open: true
    tty: true
    container_name: app.anproject
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    ports:
      - "5173:5173"
    volumes:
      - ./:/task
      # exclude
      # - /app/.git/
    working_dir: /task/app
    user: 1000:1000

  api:
    build: .docker/api
    stdin_open: true
    tty: true
    container_name: api.anproject
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    ports:
      - "3000:3000"
    volumes:
      - ./:/task
      # exclude
      # - /api/.git/
    working_dir: /task/api
    user: 1000:1000

  mysql:
    build: .docker/mysql
    container_name: mysql.anproject
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pjan
      MYSQL_USER: pjan
      MYSQL_PASSWORD: pjan
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.docker/mysql/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./database:/database:rw
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.3
    container_name: pma.anproject
    ports:
      - "8088:80"
    environment:
      PMA_HOST: mysql.anproject
      PMA_USER: pjan
      PMA_PASSWORD: pjan
      UPLOAD_LIMIT: 250M
    restart: always

volumes:
  mysql_data:
    driver: local
